---
# tasks file for ansible-role-certbot
- debug:
    msg: OS {{ ansible_os_family }}-{{ ansible_distribution_major_version | int }}

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version | int }}.yml"
    - "../vars/main.yml"

# Installing and registering certbot
- name: check if Certbot is already registered
  stat:
    path: "/etc/letsencrypt/accounts/acme.sectigo.com/"
  register: isRegistered

- name: Install Certbot
  package:
    name:
      - "{{ certbot_package_name }}"
      - "{{ python_apache_certbot_package_name }}" 
    state: latest
  when: not isRegistered.stat.exists

- name: Register and obtain certs
  block:
    - shell: certbot register --server https://acme.sectigo.com/v2/OV --agree-tos --eab-kid {{ sectigo_eab_kid }} --eab-hmac-key {{ sectigo_eab_hmac_key }} --no-eff-email --email {{ sectigo_emailAddress }}

    - name: certbot | cron.d | setup
      copy: content="{{ sectigo_cron }}" dest=/etc/cron.d/certbot mode=755 owner=root group=root

    - shell: certbot certonly --apache --server https://acme.sectigo.com/v2/OV --non-interactive --agree-tos --domain {{ sectigo_domains }} {{ sectigo_san_domains }} {{ sectigo_additional_parameters }}
      when: sectigo_san_domains is defined

    - shell: certbot certonly --apache --server https://acme.sectigo.com/v2/OV --non-interactive --agree-tos --domain {{ sectigo_domains }} {{ sectigo_additional_parameters }}
      when: sectigo_san_domains is not defined

  when: (sectigo_eab_kid is defined) and (sectigo_eab_hmac_key is defined) and (sectigo_emailAddress is defined) and (sectigo_domains is defined) and (not isRegistered.stat.exists)

# - name: Create directory structure
#   file:
#     path: "/etc/letsencrypt/{{ item }}"
#     owner: root
#     group: root
#     mode: 0755
#     recurse: yes
#     state: directory
#   with_items: ["accounts", "accounts/acme.sectigo.com", "accounts/acme.sectigo.com/v2", "accounts/acme.sectigo.com/v2/OV", "accounts/acme.sectigo.com/v2/OV/{{ sectigo_account }}"]

# - copy: content="{{ sectigo_meta|to_json }}" dest=/etc/letsencrypt/accounts/acme.sectigo.com/v2/OV/{{ sectigo_account }}/meta.json

# - copy: content="{{ sectigo_private_key|to_json }}" dest=/etc/letsencrypt/accounts/acme.sectigo.com/v2/OV/{{ sectigo_account }}/private_key.json

# - copy: content="{{ sectigo_regr|to_json }}" dest=/etc/letsencrypt/accounts/acme.sectigo.com/v2/OV/{{ sectigo_account }}/regr.json

